common/modules/mdl/models/GradeMap.php
<?php

namespace common\modules\mdl\models;

use Yii;
use common\models\Grade;

/**
 * This is the model class for table "mdl_grade_map".
 *
 * @property integer $gm_id
 * @property integer $gm_mdl_id
 * @property integer $gm_lms_id
 *
 * @property Grade $grade
 * 
 * @property DisciplineMap[] $disciplinesMap
 */
class GradeMap extends ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return parent::getPrefix() . '_grade_map';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['gm_lms_id'], 'required'],
            [['gm_mdl_id', 'gm_lms_id'], 'integer'],
            [['gm_mdl_id'], 'unique'],
            [['gm_lms_id'], 'unique'],
            [['gm_lms_id'], 'exist', 'skipOnError' => true, 'targetClass' => Grade::className(), 'targetAttribute' => ['gm_lms_id' => 'g_id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'gm_id' => Yii::t('mdl', 'Gm ID'),
            'gm_mdl_id' => Yii::t('mdl', 'Gm Mdl ID'),
            'gm_lms_id' => Yii::t('mdl', 'Gm Lms ID'),
        ];
    }

    public function init()
    {
        // create parent program mapping
        $this->on(self::EVENT_AFTER_INSERT, [$this, 'createProgramMap']);
        // create nested disciplines mapping
        $this->on(self::EVENT_AFTER_INSERT, [$this, 'createDisciplinesMap']);
        // delete nested disciplines mapping
        $this->on(self::EVENT_AFTER_DELETE, [$this, 'deleteDisciplinesMap']);
        // create nested students mapping
        $this->on(self::EVENT_AFTER_INSERT, [$this, 'createStudentsMap']);
        // delete nested students mapping
        $this->on(self::EVENT_AFTER_DELETE, [$this, 'deleteStudentsMap']);

        parent::init();
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGrade()
    {
        return $this->hasOne(Grade::className(), ['g_id' => 'gm_lms_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDisciplinesMap()
    {
        return $this->hasMany(DisciplineMap::className(), ['dm_grade_id' => 'gm_lms_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStudentsMap()
    {
        return $this->hasMany(StudentMap::className(), ['sm_lms_id' => 'r_student_id'])->viaTable(\common\models\Raise::tableName(), ['r_grade_id' => 'gm_lms_id']);
    }

    protected function createProgramMap()
    {
        $program = $this->grade->program;
        // if (lmsID is not set) and (program mapping doesn't not exist)
        if (!$this->gm_mdl_id && !ProgramMap::find()->where(['pm_lms_id' => $program->p_id])->exists()) {
            $pm = new ProgramMap();
            $pm->pm_lms_id = $program->p_id;
            // disable parent trigger for programm mapping don't create nested grades mapping
            $pm->off(ProgramMap::EVENT_AFTER_INSERT);
            $pm->save();
        }
    }

    protected function createDisciplinesMap()
    {
        foreach (Grade::findOne(['g_id' => $this->gm_lms_id])->disciplines as $d) {
            // if not exist
            if (!DisciplineMap::find()->where([
                    'dm_lms_id' => $d->d_id,
                    'dm_grade_id' => $this->gm_lms_id,
                ])->exists()) {
                $dm = new DisciplineMap();
                $dm->dm_lms_id = $d->d_id;
                $dm->dm_grade_id = $this->gm_lms_id;
                $dm->save();
            }
        }
    }

    protected function deleteDisciplinesMap()
    {
        // delete nested where mdlID is not set
        foreach ($this->getDisciplinesMap()->where(['dm_mdl_id' => null])->all() as $dm) {
            $dm->delete();
        }
    }

    protected function createStudentsMap()
    {
        foreach (Grade::findOne(['g_id' => $this->gm_lms_id])->students as $s) {
            // if not exist
            if (!StudentMap::find()->where(['sm_lms_id' => $s->s_id])->exists()) {
                $sm = new StudentMap();
                $sm->sm_lms_id = $s->s_id;
                $sm->save();
            }
        }
    }

    public function updateStudentsMap()
    {
        $this->createStudentsMap();
    }

    protected function deleteStudentsMap()
    {
        // delete nested where mdlID is not set
        foreach ($this->getStudentsMap()->where(['sm_mdl_id' => null])->all() as $sm) {
            $sm->delete();
        }
    }

    public static function listAll($field = 'grade.g_name')
    {
        $query = static::find()->joinWith('grade.program')->orderBy(['program.p_name' => SORT_ASC, 'LENGTH([[grade.g_name]])' => SORT_ASC, 'grade.g_name' => SORT_ASC]);

        return \yii\helpers\ArrayHelper::map($query->all(), 'gm_lms_id', $field, 'grade.program.p_name');
    }
}

common/modules/mdl/controllers/DefaultController.php
<?php

namespace common\modules\mdl\controllers;

use yii\web\Controller;

/**
 * Default controller for the `mdl` module
 */
class DefaultController extends Controller
{
    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }
}

common/modules/mdl/controllers/GradeMapController.php
<?php

namespace common\modules\mdl\controllers;

use Yii;
use common\modules\mdl\models\GradeMap;
use common\modules\mdl\models\GradeMapSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * GradeMapController implements the CRUD actions for GradeMap model.
 */
class GradeMapController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all GradeMap models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new GradeMapSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single GradeMap model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new GradeMap model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new GradeMap();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->gm_id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing GradeMap model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->gm_id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing GradeMap model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the GradeMap model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return GradeMap the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = GradeMap::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

common/modules/mdl/views/grade-map/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\modules\mdl\models\GradeMap */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="grade-map-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'gm_mdl_id')->textInput() ?>

    <?= $form->field($model, 'gm_lms_id')->dropDownList(\common\models\Grade::listAll())->label(Yii::t('app', 'G Name')) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

common/modules/mdl/views/grade-map/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\modules\mdl\models\GradeMapSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="grade-map-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'gm_id') ?>

    <?= $form->field($model, 'gm_mdl_id') ?>

    <?= $form->field($model, 'gm_lms_id') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

common/modules/mdl/views/grade-map/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\modules\mdl\models\GradeMap */

$this->title = Yii::t('mdl', 'Create Grade Map');
$this->params['breadcrumbs'][] = ['label' => $this->context->module->name, 'url' => ['default/index']];
$this->params['breadcrumbs'][] = ['label' => Yii::t('mdl', 'Grade Maps'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="grade-map-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

common/modules/mdl/views/grade-map/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel common\modules\mdl\models\GradeMapSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('mdl', 'Grade Maps');
$this->params['breadcrumbs'][] = ['label' => $this->context->module->name, 'url' => ['default/index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="grade-map-index">

<?php $host = $this->context->module->host; ?>
<?php Pjax::begin(); ?>    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [

            [
                'attribute' => 'gm_mdl_id',
                'headerOptions' => ['class' => 'col-xs-1'],
            ],
            [
                'attribute' => 'gm_lms_id',
                'value' => 'grade.name',
                'filter' => \common\models\Grade::listAll(),
                'label' => Yii::t('app', 'G Name'),
                'format' => 'html',
            ],

            [
                'class' => 'backend\widgets\ActionColumn',
                'template' => '{view} {update} {delete} {show}',
                'buttons' => [
                    'show' => function ($url, $model, $key) use ($host) {
                        return !$model->gm_mdl_id ? null :
                            Html::a('<span class="glyphicon glyphicon-sunglasses"></span>',
                                sprintf('%s/course/view.php?categoryid=%s', $host, $model->gm_mdl_id));
                    },
                ],
            ],
        ],
    ]); ?>
<?php Pjax::end(); ?></div>

common/modules/mdl/views/grade-map/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\modules\mdl\models\GradeMap */

$this->title = Yii::t('app', 'Update {modelClass}: ', [
    'modelClass' => 'Grade Map',
]) . $model->gm_id;
$this->params['breadcrumbs'][] = ['label' => $this->context->module->name, 'url' => ['default/index']];
$this->params['breadcrumbs'][] = ['label' => Yii::t('mdl', 'Grade Maps'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->gm_id, 'url' => ['view', 'id' => $model->gm_id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="grade-map-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

common/modules/mdl/views/grade-map/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\modules\mdl\models\GradeMap */

$this->title = $model->gm_id;
$this->params['breadcrumbs'][] = ['label' => $this->context->module->name, 'url' => ['default/index']];
$this->params['breadcrumbs'][] = ['label' => Yii::t('mdl', 'Grade Maps'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="grade-map-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->gm_id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->gm_id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'gm_id',
            'gm_mdl_id',
            'gm_lms_id',
        ],
    ]) ?>

</div>